// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: relaykeys.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InjectReportRequest_ReportType int32

const (
	InjectReportRequest_KEYBOARD InjectReportRequest_ReportType = 0
	InjectReportRequest_MOUSE    InjectReportRequest_ReportType = 1
	InjectReportRequest_CONSUMER InjectReportRequest_ReportType = 2 // For media keys like volume/mute
)

// Enum value maps for InjectReportRequest_ReportType.
var (
	InjectReportRequest_ReportType_name = map[int32]string{
		0: "KEYBOARD",
		1: "MOUSE",
		2: "CONSUMER",
	}
	InjectReportRequest_ReportType_value = map[string]int32{
		"KEYBOARD": 0,
		"MOUSE":    1,
		"CONSUMER": 2,
	}
)

func (x InjectReportRequest_ReportType) Enum() *InjectReportRequest_ReportType {
	p := new(InjectReportRequest_ReportType)
	*p = x
	return p
}

func (x InjectReportRequest_ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InjectReportRequest_ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_relaykeys_proto_enumTypes[0].Descriptor()
}

func (InjectReportRequest_ReportType) Type() protoreflect.EnumType {
	return &file_relaykeys_proto_enumTypes[0]
}

func (x InjectReportRequest_ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InjectReportRequest_ReportType.Descriptor instead.
func (InjectReportRequest_ReportType) EnumDescriptor() ([]byte, []int) {
	return file_relaykeys_proto_rawDescGZIP(), []int{0, 0}
}

type InjectReportRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          InjectReportRequest_ReportType `protobuf:"varint,1,opt,name=type,proto3,enum=relaykeys.rpc.InjectReportRequest_ReportType" json:"type,omitempty"`
	Data          []byte                         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Raw HID report bytes (e.g., 8 bytes for keyboard)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectReportRequest) Reset() {
	*x = InjectReportRequest{}
	mi := &file_relaykeys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectReportRequest) ProtoMessage() {}

func (x *InjectReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relaykeys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectReportRequest.ProtoReflect.Descriptor instead.
func (*InjectReportRequest) Descriptor() ([]byte, []int) {
	return file_relaykeys_proto_rawDescGZIP(), []int{0}
}

func (x *InjectReportRequest) GetType() InjectReportRequest_ReportType {
	if x != nil {
		return x.Type
	}
	return InjectReportRequest_KEYBOARD
}

func (x *InjectReportRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InjectReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectReportResponse) Reset() {
	*x = InjectReportResponse{}
	mi := &file_relaykeys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectReportResponse) ProtoMessage() {}

func (x *InjectReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relaykeys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectReportResponse.ProtoReflect.Descriptor instead.
func (*InjectReportResponse) Descriptor() ([]byte, []int) {
	return file_relaykeys_proto_rawDescGZIP(), []int{1}
}

func (x *InjectReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InjectReportResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_relaykeys_proto protoreflect.FileDescriptor

const file_relaykeys_proto_rawDesc = "" +
	"\n" +
	"\x0frelaykeys.proto\x12\rrelaykeys.rpc\"\xa1\x01\n" +
	"\x13InjectReportRequest\x12A\n" +
	"\x04type\x18\x01 \x01(\x0e2-.relaykeys.rpc.InjectReportRequest.ReportTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"3\n" +
	"\n" +
	"ReportType\x12\f\n" +
	"\bKEYBOARD\x10\x00\x12\t\n" +
	"\x05MOUSE\x10\x01\x12\f\n" +
	"\bCONSUMER\x10\x02\"U\n" +
	"\x14InjectReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB3Z1github.com/AceCentre/RelayKeys/internal/zmk/protob\x06proto3"

var (
	file_relaykeys_proto_rawDescOnce sync.Once
	file_relaykeys_proto_rawDescData []byte
)

func file_relaykeys_proto_rawDescGZIP() []byte {
	file_relaykeys_proto_rawDescOnce.Do(func() {
		file_relaykeys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relaykeys_proto_rawDesc), len(file_relaykeys_proto_rawDesc)))
	})
	return file_relaykeys_proto_rawDescData
}

var file_relaykeys_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relaykeys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relaykeys_proto_goTypes = []any{
	(InjectReportRequest_ReportType)(0), // 0: relaykeys.rpc.InjectReportRequest.ReportType
	(*InjectReportRequest)(nil),         // 1: relaykeys.rpc.InjectReportRequest
	(*InjectReportResponse)(nil),        // 2: relaykeys.rpc.InjectReportResponse
}
var file_relaykeys_proto_depIdxs = []int32{
	0, // 0: relaykeys.rpc.InjectReportRequest.type:type_name -> relaykeys.rpc.InjectReportRequest.ReportType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relaykeys_proto_init() }
func file_relaykeys_proto_init() {
	if File_relaykeys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relaykeys_proto_rawDesc), len(file_relaykeys_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relaykeys_proto_goTypes,
		DependencyIndexes: file_relaykeys_proto_depIdxs,
		EnumInfos:         file_relaykeys_proto_enumTypes,
		MessageInfos:      file_relaykeys_proto_msgTypes,
	}.Build()
	File_relaykeys_proto = out.File
	file_relaykeys_proto_goTypes = nil
	file_relaykeys_proto_depIdxs = nil
}
