on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest      
    steps:
    - name: Install SCService Plugin
      run:  |
        Invoke-Webrequest -Uri 'https://nsis.sourceforge.io/mediawiki/images/e/ef/NSIS_Simple_Service_Plugin_Unicode_1.30.zip' -OutFile ss.zip
        Expand-Archive ss.zip -DestinationPath .\ss
        move ss\SimpleSC.dll "C:\Program Files (x86)\NSIS\Plugins\x86-unicode\"        
    - uses: actions/checkout@v2
    - name: Install Python
      run:  |
        pip install -r requirements.txt 
        pip install -r requirements-build.txt
        python build.py
    - name: Dump cert
      uses: kitek/decode-base64-into-file-action@1.0
      with:
        encoded-value: ${{ secrets.CERTP12B64 }}
        destination-file: win-cert.p12
    - name: Sign Windows Binary
      run:  |
        & 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool.exe' sign /a /td sha256 /fd sha256 /v /f "win-cert.p12" /p "${{ secrets.CERTPASSWORD }}" /v "RelayKeys setup.exe"
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: 'Windows Release'
        path: 'RelayKeys setup.exe'
        retention-days: 
