on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest      
    steps:
    - name: Set up scoop (Windows)
      uses: brechtm/setup-scoop@v2
    - name: Install NSIS
      run: |
        scoop bucket add extras
        scoop install nsis
        Get-Command nsis
    - name: Install SCService Plugin
      run:  |
        scoop install curl unzip
        curl -oL https://nsis.sourceforge.io/mediawiki/images/e/ef/NSIS_Simple_Service_Plugin_Unicode_1.30.zip ss.zip
        unzip ss.zip
        move NSIS_Simple_Service_Plugin_Unicode\SimpleSC.dll ~\scoop\apps\nsis\3.08\Plugins\x86-unicode\
    - uses: actions/checkout@v2
    - name: Install Python
      run:  |
        scoop install python310
        pip install -r requirements.txt 
        pip install -r equirements-build.txt
        python build.py
