on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install NSIS
      run: |
        irm get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin [-OtherParameters ...]
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop bucket add extras
        scoop install nsis
    - name: Print NSIS version
      run: makensis -VERSION
    - name: Print NSIS compile flags
      run: makensis -HDRINFO
    - uses: actions/checkout@v2
    - name: Install Python
      run:  |
        scoop install python310
        pip install -r requirements.txt 
        python build.py

