on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest      
    steps:
    - name: Set up scoop (Windows)
      uses: brechtm/setup-scoop@v2
    - name: Install NSIS
      run: |
        scoop bucket add extras
        scoop install nsis
    - name: Install SCService Plugin
      run:  |
        scoop install curl unzip
        curl -L https://nsis.sourceforge.io/mediawiki/images/e/ef/NSIS_Simple_Service_Plugin_Unicode_1.30.zip --output ss.zip
        unzip ss.zip
        move SimpleSC.dll "C:\Program Files (x86)\NSIS\Plugins\x86-unicode\"        
    - uses: actions/checkout@v2
    - name: Install Python
      run:  |
        scoop install python310
        pip install -r requirements.txt 
        pip install -r requirements-build.txt
        python build.py
    - name: Sign Windows Binary
      uses: nodefactoryio/windows-codesign-action@master
      with:
        binaryPath: RelayKeys setup.exe
        verify: "true"
        keystore: ${{ secrets.CERTP12B64 }}
        password: ${{ secrets.CERTPASSWORD }}
        appName: 'RelayKeys'
