on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest      
    steps:
    - uses: sharpninja/install-scoop-action@master
      with:
        allow-install-as-admin: true
        extension: 'ps1'
    - name: Install NSIS
      run: |
        scoop bucket add extras
        scoop install nsis
    - name: Print NSIS version
      run: makensis -VERSION
    - name: Print NSIS compile flags
      run: makensis -HDRINFO
    - uses: actions/checkout@v2
    - name: Install Python
      run:  |
        scoop install python310
        pip install -r requirements.txt 
        python build.py
