on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest      
    steps:
    - name: Dump cert
      uses: kitek/decode-base64-into-file-action@1.0
      with:
        encoded-value: ${{ secrets.CERTP12B64 }}
        destination-file: win-cert.p12
